**Задача 1**

1) Распишем формулу $toprec(u, n) = argmax_i^n \; r_{ui} = argmax_i^n \; (g_u + f_i + \mu)$
	
	Заметим, что $g_u$ и $\mu$ не зависит от $i$ и одинаковы для всех айтемов, а $f_i$ - общая предпочтительность айтема, не зависящая от конкретного пользователя $\Rightarrow$ выбор построение $r_{ui}$ не зависит от параметров / признаков пользователя
2) Так как мы решаем задачу только для конкатенации, то $x_{ui} = (x_u, 0)^T + (0, x_i)^T$. Значит $toprec(u, n) = argmax_i^n \; \theta^T \cdot (x_u, 0)^T + \theta^T \cdot (0, x_i)^T + \epsilon$. Как видно, $\theta^T \cdot (x_u, 0)^T + \epsilon$ не зависят от $i \Rightarrow$ снова влияют только параметры / признаки айтема.

3) Бонусная часть. Просто совместить параметры пользователя и айтема не выйдет, потому что параметры пользователя не будут как-то влиять на параметры айтема. Надо добавить это влияние - пусть параметры пользователя $p_u \in \mathbb{R}^k$, параметры айтема $q_i \in \mathbb{R}^k$. Тогда пусть $r_{ui} \approx p_u^T q_i$. Отсюда $toprec(u, n) = argmax_i^n \; r_{ui} = argmax_i^n \; p_u^T q_i$. Мы не можем вынести $p_u^T$ из скалярного произведения, поэтому для каждого айтема будут учитываться параметры пользователя

**Задача 2**

In [ ]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import LinearOperator
from scipy.sparse.linalg import gmres, cg

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from polara import get_movielens_data

In [15]:
data, genres = get_movielens_data(get_genres=True, split_genres=False)

In [17]:
data.head()

   userid  movieid  rating
0       1     1193       5
1       1      661       3
2       1      914       3
3       1     3408       4
4       1     2355       5

In [18]:
genres.head()

   movieid                             movienm                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy